#!/usr/bin/env python

VERSION = '0.1git'
APPNAME = 'PSE11'

top = '.'
out = '../bin'

def options(opt):
    pass

def configure(conf):
    conf.load('java')
    conf.find_program('java', var='JAVA')
    conf.find_program('cp', var='CP')
    conf.check_java_class('org.antlr.Tool')
    conf.check_java_class('org.eclipse.swt.SWT')

def build(bld):
    bld(rule = '${JAVA} org.antlr.Tool -make -fo antlr/WhileLanguage ../src/grammar/WhileLanguage.g;' 
	'${CP} -u antlr/WhileLanguage/*.java ../src/pse11/parser/', always=True)
    bld(rule = '${JAVA} org.antlr.Tool -make -fo antlr/Z3 ../src/grammar/z3.g;'
        '${CP} -u antlr/Z3/*.java ../src/pse11/verifier/smtlib/z3', always=True)
    bld(features = 'javac jar',
        srcdir   = 'pse11/',
        outdir   = 'pse11',
        basedir  = 'pse11',
	jaropts  = ['-C', '../src/pse11', 'gui/image'],
        destfile = 'pse11.jar'
    )

